### ISSUE TITLE
Manipulating Data

### ISSUE THREAD

**Issue by betsyhenson** [WL-Biol185-ShinyProjects/Oral-Health-Trends#2]
manipulating our data set into multiple tables to make the data easier to work with once in R
things we want to exclude: geographic location, data source, data value type, response, data value unit,  high confidence interval, low confidence interval, data value footnote symbol, data value footnote, soutUSfirst, breakout ID, indicator ID

**Comment by teawdatwanf19** [comment]
Goal is to have data tidied and spread into their perspective tables so we can begin coding
